"""empty message

Revision ID: ae3554c75b6a
Revises: 
Create Date: 2017-08-07 04:36:32.972440

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'ae3554c75b6a'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('gatepersonnel')
    op.drop_table('rfidtag')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('rfidtag',
    sa.Column('uuid', postgresql.UUID(), autoincrement=False, nullable=False),
    sa.Column('rfidTagId', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('uuid', name=u'rfidtag_pkey'),
    postgresql_ignore_search_path=False
    )
    op.create_table('gatepersonnel',
    sa.Column('uuid', postgresql.UUID(), autoincrement=False, nullable=False),
    sa.Column('playaName', sa.VARCHAR(length=64), autoincrement=False, nullable=True),
    sa.Column('currentRfidTagIDs', postgresql.UUID(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['currentRfidTagIDs'], [u'rfidtag.uuid'], name=u'gatepersonnel_currentRfidTagIDs_fkey'),
    sa.PrimaryKeyConstraint('uuid', name=u'gatepersonnel_pkey')
    )
    # ### end Alembic commands ###
